In [12]:
import torch
print(torch.__version__)

2.8.0+cu126


In [13]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [13]:
# using empty
a = torch.empty(2,3)

In [14]:
# check type
type(a)

torch.Tensor

In [15]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
# using rand
torch.rand(2,3)

tensor([[0.1185, 0.4362, 0.2218],
        [0.4207, 0.5561, 0.5820]])

In [18]:
# use of seed
torch.rand(2,3)

tensor([[0.6633, 0.1561, 0.6333],
        [0.1660, 0.5728, 0.6335]])

In [19]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [20]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [23]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [29]:
# find data type
x.dtype

torch.int64

In [30]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [32]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [33]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [34]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [35]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [36]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [37]:
c = torch.tensor([1, -2, 3, -4])

In [38]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [41]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [42]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [43]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [44]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [45]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [46]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [47]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [48]:
# median
torch.median(e)

tensor(0.)

In [49]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [50]:
# product
torch.prod(e)

tensor(0.)

In [51]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [52]:
# variance
torch.var(e)

tensor(19.6000)

In [53]:
# argmax
torch.argmax(e)

tensor(5)

In [54]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [55]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [56]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [57]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [58]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [59]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [60]:
# determinant
torch.det(h)

tensor(-110.)

In [61]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [62]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [63]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [64]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [65]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [66]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [67]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [68]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [69]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [70]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [71]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [72]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [73]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [74]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [75]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [76]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [77]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [21]:
a = torch.rand(2,3)
a

tensor([[0.8416, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [22]:
b = a

In [23]:
b

tensor([[0.8416, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [24]:
a[0][0] = 0

In [25]:
a

tensor([[0.0000, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [26]:
b

tensor([[0.0000, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [27]:
id(a)

134456140125344

In [28]:
id(b)

134456140125344

In [29]:
b = a.clone()

In [30]:
a

tensor([[0.0000, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [31]:
b

tensor([[0.0000, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [32]:
a[0][0] = 10

In [33]:
a

tensor([[10.0000,  0.2621,  0.7439],
        [ 0.9182,  0.0101,  0.0618]])

In [34]:
b

tensor([[0.0000, 0.2621, 0.7439],
        [0.9182, 0.0101, 0.0618]])

In [35]:
id(a)

134456140125344

In [36]:
id(b)

134456421171520

Run tensor on GPU

In [37]:
torch.cuda.is_available()

True

In [38]:
device = torch.device('cuda')

In [97]:
torch.rand(2,3)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [43]:
#moving tensor on cpu to gpu
c = torch.rand(2,3)


In [44]:
c.to(device)

tensor([[0.6186, 0.3421, 0.2818],
        [0.7644, 0.7502, 0.8838]], device='cuda:0')

reshape tenson

In [66]:
a = torch.ones(5,5)
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [70]:
# Valid reshape operations
# Reshape to 5x5 (no change in shape, just a reshape operation)
print(a.reshape(5, 5))

# Reshape to a 1D tensor of 25 elements
print(a.reshape(1, 25))

# You can also use -1 to infer one dimension
print(a.reshape(-1)) # Reshapes to a 1D tensor

# Reshape to a 5xsomething tensor
print(a.reshape(5, -1))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [71]:
a.flatten()


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.])

In [72]:
b = torch.rand(2,3,4)
b

tensor([[[0.8917, 0.8059, 0.3463, 0.3113],
         [0.0191, 0.8782, 0.5455, 0.6661],
         [0.7751, 0.8207, 0.0338, 0.9826]],

        [[0.6611, 0.9338, 0.6698, 0.1626],
         [0.0976, 0.0323, 0.5265, 0.6345],
         [0.0435, 0.6027, 0.8019, 0.4169]]])

In [73]:
b.permute(2,1,0)

tensor([[[0.8917, 0.6611],
         [0.0191, 0.0976],
         [0.7751, 0.0435]],

        [[0.8059, 0.9338],
         [0.8782, 0.0323],
         [0.8207, 0.6027]],

        [[0.3463, 0.6698],
         [0.5455, 0.5265],
         [0.0338, 0.8019]],

        [[0.3113, 0.1626],
         [0.6661, 0.6345],
         [0.9826, 0.4169]]])

In [74]:
c = torch.rand(2,3,4)
c

tensor([[[0.2486, 0.3862, 0.8421, 0.4297],
         [0.8655, 0.8503, 0.9879, 0.8437],
         [0.7696, 0.9374, 0.4100, 0.2945]],

        [[0.3385, 0.7756, 0.7100, 0.7513],
         [0.5215, 0.8939, 0.4024, 0.8105],
         [0.5861, 0.0249, 0.2464, 0.7303]]])

In [75]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [77]:
c = torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [78]:
d = torch.rand(1,20)
d.squeeze(0)

tensor([0.8427, 0.5709, 0.7369, 0.4432, 0.6890, 0.1140, 0.7744, 0.7442, 0.2585,
        0.9836, 0.5129, 0.1845, 0.5607, 0.2358, 0.0100, 0.1457, 0.7563, 0.0557,
        0.4445, 0.7853])

numpy and pytorch

In [80]:
import numpy as np

In [82]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [84]:
b = a.numpy()

In [85]:
b

array([1, 2, 3])

In [86]:
type(b)

numpy.ndarray

In [87]:
c = np.array([1,2,3])

In [88]:
c

array([1, 2, 3])

In [89]:
torch.from_numpy(c)

tensor([1, 2, 3])